// supabase/functions/fetch-fmp-exchange-prices-api/types.ts

// Interface for data fetched from the FMP /api/v3/quotes/{EXCHANGE} endpoint
export interface FmpExchangeQuoteData {
  symbol: string;
  name?: string | null;
  price: number;
  changesPercentage?: number | null;
  change?: number | null;
  dayLow?: number | null;
  dayHigh?: number | null;
  yearHigh?: number | null;
  yearLow?: number | null;
  marketCap?: number | null;
  priceAvg50?: number | null;
  priceAvg200?: number | null;
  exchange?: string | null;
  volume?: number | null;
  avgVolume?: number | null;
  open?: number | null;
  previousClose?: number | null;
  eps?: number | null;
  pe?: number | null;
  earningsAnnouncement?: string | null;
  sharesOutstanding?: number | null;
  timestamp: number; // Unix timestamp (seconds) from FMP
}

// Interface for the record to be upserted into your 'live_quote_indicators' table
export interface LiveQuoteIndicatorRecord {
  symbol: string; // Primary key / conflict target
  current_price: number;
  change_percentage?: number | null;
  day_change?: number | null;
  volume?: number | null;
  day_low?: number | null;
  day_high?: number | null;
  market_cap?: number | null;
  day_open?: number | null;
  previous_close?: number | null;
  api_timestamp: number; // From FMP's 'timestamp' (in seconds)
  sma_50d?: number | null;
  sma_200d?: number | null;
  fetched_at: string; // ISO string, generated by the function
  year_high?: number | null;
  year_low?: number | null;
  exchange?: string | null;
}

// Interface for summarizing the result of processing each exchange's quotes
export interface ExchangeQuoteProcessingResult {
  exchange: string;
  success: boolean;
  message: string;
  recordsProcessed: number;
}

// Interface for the overall response of the Edge Function
export interface ExchangeQuoteFunctionResponse {
  message: string;
  details: ExchangeQuoteProcessingResult[];
  totalProcessed: number;
  totalSucceeded: number;
}

