// supabase/functions/fetch-fmp-profiles/types.ts

// Interface for the data structure from FMP API /profile endpoint
// Based on the provided schema and typical FMP responses.
export interface FmpProfileData {
  symbol: string;
  price: number;
  marketCap: number;
  beta: number;
  lastDividend: number;
  range: string;
  change: number;
  changePercentage: number;
  volume: number;
  averageVolume: number;
  companyName: string;
  currency: string;
  cik: string;
  isin: string;
  cusip: string;
  exchangeFullName: string;
  exchange: string;
  industry: string;
  website: string;
  description: string;
  ceo: string;
  sector: string;
  country: string;
  fullTimeEmployees: string; // FMP provides this as a string in the example
  phone: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  image: string;
  ipoDate: string; // "YYYY-MM-DD"
  defaultImage: boolean;
  isEtf: boolean;
  isActivelyTrading: boolean;
  isAdr: boolean;
  isFund: boolean;
}

// Interface for the record to be upserted into your 'profiles' table
// This should match your Supabase table schema exactly.
export interface SupabaseProfileRecord {
  symbol: string; // Primary key for upsert conflict
  price?: number | null;
  market_cap?: number | null;
  beta?: number | null;
  last_dividend?: number | null;
  range?: string | null;
  change?: number | null;
  change_percentage?: number | null;
  volume?: number | null;
  average_volume?: number | null;
  company_name?: string | null;
  currency?: string | null;
  cik?: string | null;
  isin?: string | null;
  cusip?: string | null;
  exchange_full_name?: string | null;
  exchange?: string | null;
  industry?: string | null;
  website?: string | null;
  description?: string | null;
  ceo?: string | null;
  sector?: string | null;
  country?: string | null;
  full_time_employees?: number | null; // Needs conversion if FMP provides string
  phone?: string | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  zip?: string | null;
  image?: string | null;
  ipo_date?: string | null; // Ensure "YYYY-MM-DD" format or null
  default_image?: boolean | null;
  is_etf?: boolean | null;
  is_actively_trading?: boolean | null;
  is_adr?: boolean | null;
  is_fund?: boolean | null;
  // id will be auto-generated by Supabase if not provided or handled by DB default
  // modified_at will be handled by the trigger
}

export interface SupportedSymbol {
  symbol: string;
  // last_processed_profile_at?: string | null; // Optional, if you add this to your table
}

export interface SymbolProcessingResult {
  symbol: string;
  success: boolean;
  message: string;
  data?: FmpProfileData | null; // Optional: include fetched data in result for logging
}

export interface FunctionResponse {
  message: string;
  details: SymbolProcessingResult[];
  totalProcessed: number;
  totalSucceeded: number;
  totalUpserted: number;
}
