// supabase/functions/fetch-fmp-batch-quote-indicators/types.ts

// Interface for data fetched from the FMP /api/v4/batch-pre-post-market endpoint
export interface FmpBatchQuoteData {
  symbol: string;
  ask: number;
  bid: number;
  asize: number;
  bsize: number;
  timestamp: number; // Unix timestamp (milliseconds) from FMP
}

// Interface for the record to be upserted into your 'live_quote_indicators' table
export interface LiveQuoteIndicatorRecord {
  symbol: string; // Primary key / conflict target
  current_price: number; // Using ask price from batch API
  change_percentage?: number | null;
  day_change?: number | null;
  volume?: number | null;
  day_low?: number | null;
  day_high?: number | null;
  market_cap?: number | null;
  day_open?: number | null;
  previous_close?: number | null;
  api_timestamp: number; // From FMP's 'timestamp' (converted to seconds)
  sma_50d?: number | null;
  sma_200d?: number | null;
  fetched_at: string; // ISO string, generated by the function
  year_high?: number | null;
  year_low?: number | null;
  exchange?: string | null;
}

// Interface for rows from 'supported_symbols' table
export interface SupportedSymbol {
  symbol: string;
}

// Interface for summarizing the result of processing each symbol's quote
export interface SymbolQuoteProcessingResult {
  symbol: string;
  success: boolean;
  message: string;
}

// Interface for the overall response of the Edge Function
export interface QuoteFunctionResponse {
  message: string;
  details: SymbolQuoteProcessingResult[];
  totalProcessed: number;
  totalSucceeded: number;
}

