#!/usr/bin/env sh
# The above line (shebang) is optional for modern Husky but good practice.

# Exit immediately if a command exits with a non-zero status.
set -e

# Run lint-staged
npx lint-staged
npx playwright test --reporter=list
npm run build